packages:
  - apps/*
  - libs/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - '@sentry/capacitor'
  - '@sentry/cli'
  - '@swc/core'
  - cypress
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - protobufjs
  - puppeteer
  - re2
  - unrs-resolver
