import { Component, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, ActivatedRouteSnapshot, NavigationEnd, Router } from '@angular/router';
import { filter, map, startWith } from 'rxjs/operators';
import { IonApp, IonButtons, IonContent, IonHeader, IonItem, IonLabel, IonMenu, IonRouterOutlet, IonSplitPane, IonToolbar, ModalController } from '@ionic/angular/standalone';

import { AppStore } from '@bk2/shared-feature';
import { RoleName } from '@bk2/shared-models';
import { Spinner, ConnectionStatusButton, AvatarUser } from '@bk2/shared-ui';
import { coerceBoolean, getImgixUrlWithAutoParams, hasRole } from '@bk2/shared-util-core';

import { AuthInfo } from '@bk2/auth-ui';
import { Menu } from '@bk2/cms-menu-feature';
import { ProfileEditModal } from '@bk2/profile-feature';
import { CookieBanner } from '@bk2/consent-ui';
import { ConsentService } from '@bk2/consent-data-access';

@Component({
  imports: [
    Menu, AuthInfo, Spinner, ConnectionStatusButton, AvatarUser, CookieBanner,
    IonApp, IonSplitPane, IonMenu, IonHeader, IonContent, IonToolbar, IonRouterOutlet, IonButtons,
    IonLabel, IonItem
],
  selector: 'bk-root',
  standalone: true,
  styles: [
    `
      /* ----------------------------------------------
    * Generated by Animista on 2024-8-1 15:19:28
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

      /**
    * ----------------------------------------
    * animation kenburns-top
    * ----------------------------------------
    */
      @-webkit-keyframes kenburns-top {
        0% {
          -webkit-transform: scale(1) translateY(0);
          transform: scale(1) translateY(0);
          -webkit-transform-origin: 50% 16%;
          transform-origin: 50% 16%;
        }
        100% {
          -webkit-transform: scale(1.25) translateY(-15px);
          transform: scale(1.25) translateY(-15px);
          -webkit-transform-origin: top;
          transform-origin: top;
        }
      }
      @keyframes kenburns-top {
        0% {
          -webkit-transform: scale(1) translateY(0);
          transform: scale(1) translateY(0);
          -webkit-transform-origin: 50% 16%;
          transform-origin: 50% 16%;
        }
        100% {
          -webkit-transform: scale(1.25) translateY(-15px);
          transform: scale(1.25) translateY(-15px);
          -webkit-transform-origin: top;
          transform-origin: top;
        }
      }

      .logo-container {
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #1a5fab;
        height: 100%;
      }
      .kenburns-top {
        -webkit-animation: kenburns-top 1s cubic-bezier(0.6, -0.28, 0.735, 0.045) both;
        animation: kenburns-top 1s cubic-bezier(0.6, -0.28, 0.735, 0.045) both;
        margin: 0 auto;
        display: block;
        width: 33%;
      }
      /* Covers the (always-mounted) router outlet while the app is not yet ready. */
      .app-ready-overlay {
        position: absolute;
        inset: 0;
        z-index: 10;
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--ion-background-color, #fff);
      }
    `,
  ],
  template: `
    @defer {
    <!--
        bk app has one single, left menu -> main-menu
        menuitem contents are dependent on e.g. authentication and user role
        register all menus here, derive them from BaseMenu and set a menu id within the class
        use MenuController with this.menu.enable(true, menuId) to switch the menus
      -->
    <ion-app>
      <bk-cookie-banner />
      <ion-split-pane contentId="main" [disabled]="!showMenu()">
        @if(showMenu()) {
        <ion-menu side="start" menuId="main" contentId="main" type="overlay">
          <ion-header>
            <ion-toolbar color="secondary">
              <ion-buttons slot="start">
                <bk-connection-status-button />
              </ion-buttons>
              <ion-item lines="none" color="secondary">
                <ion-label>{{ appStore.appConfig().appName }}</ion-label>
              </ion-item>
              @if(appStore.currentUser(); as currentUser) {
                <ion-buttons slot="end">
                  <bk-avatar-user [currentUser]="currentUser" (profileClicked)="openProfile()" />
                </ion-buttons>
              }
            </ion-toolbar>
          </ion-header>
          <ion-content>
            @if (isUserSessionReady()) {
              <bk-menu [menuName]="mainMenuName()" />
            } @else {
              <bk-spinner />
            }
            @if(showDebugInfo()) {
              <bk-auth-info [currentUser]="appStore.currentUser()" [fbUser]="appStore.fbUser()" [isAuthenticated]="appStore.isAuthenticated()" [isAdmin]="hasRole('admin')" />
            }
          <ion-item lines="none" button detail="false" (click)="openCookieSettings()">
            <ion-label color="medium" style="font-size: 13px;">Cookie-Einstellungen</ion-label>
          </ion-item>
          </ion-content>
        </ion-menu>
        }
        <!--
          The element with id="main" MUST always be in the DOM. Both ion-split-pane
          (styleMainElement) and ion-menu (getElementById) resolve contentId="main"
          exactly once at connect time and never re-check. Gating the outlet out of
          the DOM during the not-ready window detaches the menu (renders transparent
          and non-interactive) and triggers the
          "[ion-split-pane] - Does not have a specified main node." warning. So keep a
          stable #main wrapper as the split-pane content and gate only the feature
          content inside it. The .ion-page class fills the pane when the split-pane is
          disabled/not-visible (matching ion-router-outlet's own absolute fill).
        -->
        <div id="main" class="ion-page">
          <!--
            The <ion-router-outlet> must ALWAYS stay in the DOM. Removing it (e.g. via
            @if) while an Ionic navigation transition is in flight destroys the
            StackController and crashes with "can't access property 'commit', d is
            undefined" (StackController.transition reads the cleared containerEl). Feature
            routes are instead held until the app is ready by isAppReadyGuard (see
            app.routes.ts); here we only overlay a spinner on top of the still-mounted
            outlet during the not-ready window.
          -->
          <ion-router-outlet />
          @if (!isAppReady()) {
            <div class="app-ready-overlay">
              <bk-spinner />
            </div>
          }
        </div>
      </ion-split-pane>
    </ion-app>
    } @placeholder (minimum 1000ms) {
    <div class="logo-container">
      <img class="kenburns-top" [src]="logoUrl()" alt="logo" />
    </div>
    } @loading(after 100ms; minimum 500ms) {
    <span>Bitte warten... die Applikation wird geladen.</span>
    } @error {
    <span>Oops ! Die Applikation konnte nicht geladen werden. Bitte nochmals probieren.</span>
    }
  `,
})
export class BkRoot {
  protected appStore = inject(AppStore);
  private readonly modalController = inject(ModalController);
  protected readonly consentService = inject(ConsentService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly queryParamMap = toSignal(this.route.queryParamMap);
  private readonly showMenuFromRoute = toSignal(
    this.router.events.pipe(
      filter(e => e instanceof NavigationEnd),
      startWith(null),
      map(() => this.findRouteData('showMenu'))
    ),
    { initialValue: undefined as boolean | undefined }
  );
  protected readonly showMenu = computed(() => {
    const qp = this.queryParamMap()?.get('showMenu');
    if (qp != null) return coerceBoolean(qp);
    return this.showMenuFromRoute() ?? true;
  });

  private findRouteData(key: string): boolean | undefined {
    let snapshot: ActivatedRouteSnapshot | null = this.router.routerState.snapshot.root;
    let result: boolean | undefined;
    while (snapshot) {
      if (snapshot.data?.[key] !== undefined) result = coerceBoolean(snapshot.data[key]);
      snapshot = snapshot.firstChild;
    }
    return result;
  }

  protected showDebugInfo = computed(() => this.appStore.showDebugInfo());
  protected mainMenuName = computed(() => `main_${this.appStore.tenantId()}`);
  protected logoUrl = computed(() => `${this.appStore.services.imgixBaseUrl()}/${getImgixUrlWithAutoParams(this.appStore.appConfig().logoUrl)}`);

  // Single source of truth lives on the AppStore (also consumed by isAppReadyGuard).
  // isUserSessionReady gates the menu spinner; isAppReady gates the outlet overlay.
  protected isUserSessionReady = this.appStore.isUserSessionReady;
  protected isAppReady = this.appStore.isAppReady;

  protected hasRole(role: RoleName | undefined): boolean {
    return hasRole(role, this.appStore.currentUser());
  }

  protected openCookieSettings(): void {
    this.consentService.reset();
  }

  protected async openProfile(): Promise<void> {
    const modal = await this.modalController.create({
      component: ProfileEditModal,
    });
    modal.present();
    await modal.onDidDismiss();
  }
}
