export type WorkrelNewFormModel = {
    tags: string;
    notes: string;
    subjectKey: string;
    subjectName1: string;
    subjectName2: string;
    subjectType: string;
    objectKey: string;
    objectName: string;
    objectType: string;
    type: string;
    label: string;
    validFrom: string;
    validTo: string;
    price: number;
    currency: string;
    periodicity: string;
    order: number;
    state: string;
};
export declare const WORKREL_NEW_FORM_SHAPE: WorkrelNewFormModel;
