import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { ErrorEvent } from '@sentry/angular';
import { beforeSend, buildSentryOptions, SentryConfig } from './sentry';

const cfg: SentryConfig = {
  dsn: 'https://abc@o1.ingest.de.sentry.io/2',
  environment: 'production',
  release: 'scs@1.2.3',
  tracesSampleRate: 0.1,
  enabled: true,
};

describe('buildSentryOptions', () => {
  it('passes through dsn, environment, release and enabled', () => {
    const o = buildSentryOptions(cfg, []);
    expect(o.dsn).toBe(cfg.dsn);
    expect(o.environment).toBe('production');
    expect(o.release).toBe('scs@1.2.3');
    expect(o.enabled).toBe(true);
  });

  it('never auto-attaches PII and always installs beforeSend', () => {
    const o = buildSentryOptions(cfg, []);
    expect(o.sendDefaultPii).toBe(false);
    expect(o.beforeSend).toBe(beforeSend);
  });

  it('suppresses transient aborted-request JSON-EOF noise across browsers', () => {
    const patterns = (buildSentryOptions(cfg, []).ignoreErrors ?? []) as RegExp[];
    const matches = (msg: string) => patterns.some((p) => p instanceof RegExp && p.test(msg));
    // Safari, V8/Chrome and Firefox variants of an empty/truncated JSON body.
    expect(matches('JSON Parse error: Unexpected EOF')).toBe(true);
    expect(matches('Unexpected end of JSON input')).toBe(true);
    expect(matches('JSON.parse: unexpected end of data')).toBe(true);
    // Must NOT swallow a genuinely malformed-content parse error.
    expect(matches('JSON Parse error: Unexpected token "<"')).toBe(false);
  });

  it('suppresses browser-extension runtime.sendMessage noise (SCS-2B)', () => {
    const patterns = (buildSentryOptions(cfg, []).ignoreErrors ?? []) as RegExp[];
    const matches = (msg: string) => patterns.some((p) => p instanceof RegExp && p.test(msg));
    expect(matches('Error: Invalid call to runtime.sendMessage(). Tab not found.')).toBe(true);
    expect(matches('Failed to send message to the server')).toBe(false);
  });

  it('drops events originating inside the Google reCAPTCHA script (SCS-1Q)', () => {
    const patterns = (buildSentryOptions(cfg, []).denyUrls ?? []) as RegExp[];
    const matches = (url: string) => patterns.some((p) => p instanceof RegExp && p.test(url));
    // Frame filenames as they appear in real events: relative (first-party-looking) and absolute.
    expect(matches('/recaptcha/releases/A7KpaEASfhDcK0nXxgQEyyYv/recaptcha__en.js')).toBe(true);
    expect(matches('https://www.google.com/recaptcha/releases/abc/recaptcha__en.js')).toBe(true);
    expect(matches('https://www.gstatic.com/recaptcha/releases/abc/recaptcha__de.js')).toBe(true);
    // Must NOT swallow our own bundles.
    expect(matches('https://seeclub.org/main-ABC123.js')).toBe(false);
  });
});

describe('beforeSend', () => {
  // The suite's jsdom origin is a localhost dev-server URL; simulate a deployed
  // origin so the dev-server guard doesn't swallow the events under test.
  beforeEach(() => vi.stubGlobal('location', new URL('https://seeclub.org/')));
  afterEach(() => vi.unstubAllGlobals());

  it('drops development events entirely', () => {
    const event = { environment: 'development', message: 'boom' } as ErrorEvent;
    expect(beforeSend(event, {})).toBeNull();
  });

  it('drops events served from a localhost dev server even when the baked-in config claims production', () => {
    // A stale tab can run a bundle whose environment.ts was generated by a release
    // build (SCS-1N): environment says 'production' but the page is localhost:4201.
    vi.stubGlobal('location', new URL('http://localhost:4201/public/news'));
    const event = { environment: 'production', message: 'Failed to fetch dynamically imported module' } as ErrorEvent;
    expect(beforeSend(event, {})).toBeNull();
  });

  it('drops the stale-chunk error it is already recovering from (SCS-1N)', async () => {
    // Fresh module registry so the recovery flag starts unset and both modules share it.
    vi.resetModules();
    const { recoverFromStaleChunk } = await import('./chunk-load-error-handler');
    const { beforeSend: freshBeforeSend } = await import('./sentry');
    const event = () => ({ environment: 'production', message: 'boom' }) as ErrorEvent;

    expect(freshBeforeSend(event(), {})).not.toBeNull();

    sessionStorage.clear();
    vi.stubGlobal('location', Object.assign(new URL('https://seeclub.org/'), { reload: vi.fn() }));
    expect(recoverFromStaleChunk(new Error('Failed to fetch dynamically imported module: https://x/src-AB12.js'))).toBe(true);

    // The reload is under way — every event from this dying page is now noise.
    expect(freshBeforeSend(event(), {})).toBeNull();
  });

  it('keeps events from Capacitor native shells (localhost without an explicit port)', () => {
    vi.stubGlobal('location', new URL('https://localhost/home'));
    const event = { environment: 'production', message: 'boom' } as ErrorEvent;
    expect(beforeSend(event, {})).not.toBeNull();
  });

  it('redacts the message of a production event', () => {
    const event = { environment: 'production', message: 'fail for a@b.ch' } as ErrorEvent;
    const out = beforeSend(event, {});
    expect(out?.message).toBe('fail for [EMAIL]');
  });

  it('redacts exception values and breadcrumb messages', () => {
    const event = {
      environment: 'production',
      exception: { values: [{ value: 'AHV 756.1234.5678.90' }] },
      breadcrumbs: [{ message: 'iban CH93 0076 2011 6238 5295 7' }],
    } as unknown as ErrorEvent;
    const out = beforeSend(event, {});
    expect(out?.exception?.values?.[0].value).toContain('[AHV]');
    expect(out?.breadcrumbs?.[0].message).toContain('[IBAN]');
  });
});
