import { Component, computed, input, model } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IonInput, IonInputPasswordToggle, IonItem, IonNote } from '@ionic/angular/standalone';

import { MaskitoDirective } from '@maskito/angular';
import { MaskitoElementPredicate, MaskitoOptions } from '@maskito/core';

import { AnyCharMask } from '@okr/shared-config';
import { InputMode, PASSWORD_MAX_LENGTH } from '@okr/shared-constants';
import { coerceBoolean } from '@okr/shared-util-core';

import { ButtonCopy, ButtonCopyI18n } from './button-copy';
import { SkipClearTab } from './skip-clear-tab.directive';

export interface PasswordInputI18n {
  name: string;
  label: string;
  placeholder: string;
  helper?: string;
  copy_conf?: string;
}

@Component({
  selector: 'okr-password-input',
  standalone: true,
  imports: [
    SkipClearTab,
    FormsModule,
    ButtonCopy,
    MaskitoDirective,
    IonItem, IonNote, IonInput, IonInputPasswordToggle
  ],
  styles: [`ion-item.helper { --min-height: 0; }`],
  template: `
    <ion-item lines="none" [button]="false">
      @if(mask(); as mask) {
        <ion-input
          type="password"
          [name]="i18n().name"
          [ngModel]="value()"
          (ngModelChange)="value.set($event)"
          labelPlacement="floating"
          [label]="i18n().label"
          [placeholder]="i18n().placeholder"
          [inputMode]="inputMode()"
          [maxlength]="maxLength()"
          [clearInput]="shouldClearInput()"
          [counter]="true"
          [autocomplete]="autocomplete()"
          [maskito]="mask"
          [maskitoElement]="maskPredicate"
        >
          <ion-input-password-toggle slot="end" tabindex="-1"></ion-input-password-toggle>
        </ion-input>
        @if (isCopyable()) {
          <okr-button-copy [i18n]="buttonCopyI18n()" [value]="value()" tabindex="-1" />
        }
      }
    </ion-item>
    @if(i18n().helper) {
      <ion-item lines="none" class="helper" [button]="false">
        <ion-note>{{ i18n().helper }}</ion-note>
      </ion-item>
    }
  `
})
export class PasswordInput {
  // inputs
  public value = model.required<string>(); // mandatory view model
  public i18n = input.required<PasswordInputI18n>();
  public maxLength = input(PASSWORD_MAX_LENGTH); // max number of characters allowed
  public clearInput = input(true); // show an icon to clear the input field
  public copyable = input(true); // if true, a button to copy the value of the input field is shown
  public inputMode = input<InputMode>('text'); // A hint to the browser for which keyboard to display.

  /**
   * Which password the browser should offer here. `current-password` lets iOS/Safari autofill a
   * SAVED password; `new-password` is what makes it offer to GENERATE a strong one and store it.
   * Getting this wrong on a set-password screen is not cosmetic: iOS then proposes the old
   * password instead of a new one, and the keychain has nothing to attach the entry to.
   */
  public autocomplete = input<'current-password' | 'new-password'>('current-password');

  // coerced boolean inputs
  protected shouldClearInput = computed(() => coerceBoolean(this.clearInput()));
  protected isCopyable = computed(() => coerceBoolean(this.copyable()));

  protected buttonCopyI18n = computed(() => ({ copy_conf: this.i18n().copy_conf } as ButtonCopyI18n));

  // AnyCharMask, not PasswordMask: a mask on a password field silently DELETES every character
  // outside its allow-list as the user types, so a password generated by iOS or a password manager
  // arrives mangled and the user gets no message. Nothing parses this value, so there is nothing to
  // enforce here — length is checked by the field's Vest suite.
  public mask = input<MaskitoOptions>(AnyCharMask);
  readonly maskPredicate: MaskitoElementPredicate = async (el) => (el as unknown as HTMLIonInputElement).getInputElement();
}
