export enum FileTypeIcon {
  Audio = 'audio',
  Code = 'code',
  Csv = 'csv',
  Doc = 'doc',
  File = 'file',
  Html = 'html',
  Image = 'image',
  Key = 'key',
  Numbers = 'numbers',
  Pages = 'pages',
  Pdf = 'pdf',
  Ppt = 'ppt',
  Txt = 'txt',
  Video = 'video',
  Xls = 'xls',
  Zip = 'zip',
}
